# Site settings
title: "yg log --graph --oneline --all"
description: > 
  프로그래밍, AI논문 리뷰, 툴, 환경등을 소개합니다.

author: yugeon
email: 23010524@sju.ac.kr
github_username: yg2127

baseurl: "" # the subpath of your site, e.g. /blog
lang: ko-KR

timezone: Asia/Seoul
url: "https://yg2127.github.io" # the base hostname & protocol for your site



# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

# Header background style: "terminal" (git log) or "grass" (contribution graph)
header_style: "terminal"

